### ISSUE TITLE
Hey this isnt a issue more than a question.. I am using a different HUD system called VMS HUD and its all open source to what I am aware of

### ISSUE THREAD

**Issue by Esole71** [MaDHouSe79/mh-cashasitem#18]
I am looking to make this work for your script instead of QB-HUD

**Comment by MaDHouSe79** [comment]
Hi, you need to check if you have `TriggerServerEvent("QBCore:Server:OnMoneyChange")` in your vms hud client side code, if not you must ask the owner of your script to add it, because it uses a money change trigger and if you don't have that it will not work.

your hud must work with money, if not than the hud will not work with this, and you need to ask the owner of the script to add this money stuff so the hud can work with this, or give him the trigger i just add above, and ask the owner to add it.
cause most huds use a money change function and the trigger above is used in that function, so it must exsist already.

**Comment by Esole71** [comment]
I am going to check right now

**Comment by bypulsar** [comment]
I am going to check this now and see what I can do!

**Comment by bypulsar** [comment]
The issue has been fixed I contacted him and his code worked fine.

**Comment by MaDHouSe79** [comment]
i never said that his code does not work, i said you need to ask him to add the trigger i gave you to add in the code where the money change happens in his hud, and then i said if he had this money change function, but you have to ask him and let him add the code for you, cause i need your code to add it and i dont have it cause you pay for it and thats ok and that why i said ask the owner to add that trigger in the hud script 😄
