### ISSUE TITLE
kep getting this error

### ISSUE THREAD

**Issue by dmoore6688** [MaDHouSe79/mh-cashasitem#21]
c-scripting-core] InvokeNative: execution failed: Argument at index 1 was null.
[ script:ps-inventory] SCRIPT ERROR: Execution of native 000000002f7a49e6 in script host failed: Argument at index 1 was null.

**Comment by MaDHouSe79** [comment]
Most of the time this error is that the server don't know the client id to send to, see when this happens, cause whitout that i can't do much.

**Comment by dmoore6688** [comment]
I happens when I try and open my inventory. I've gone back and put all steps in about five times today and its only when I take out both server and client mains and replace them with original ps-inventory it goes back to letting me open inventory. So what I'm saying is I can't open my inventory and when I try thats when it brings up the error.

**Comment by dmoore6688** [comment]
Also this line of code is not very specific to where it needs to be replaced in the server main lua. I'm not sure if that is causing it but something doesnt seem to add up. Replace this code in ps-inventory/server/main.lua it just says replace but that line of code is not in and when I search for it it does not appear.

**Comment by MaDHouSe79** [comment]
but this script does not do anything than only update the item, the inventory is a other part for moving slots, and when it opend this scripts only checks if you have the item but the inventory sends the request, so maby you add the wrong value in the triggers and thats maby why it can't send, cause you need a lot of triggers in the inventory to make this script work, like 32 triggers or even more in de server/main.lua.

**Comment by ItsJustifY** [comment]
yeah for ps-inventory only use the qb-inventory README so you might wanna tweak your instructions @MaDHouSe79

**Comment by MaDHouSe79** [comment]
@ItsJustifY, If you have a other inventory as qb-inventory or ps-inventory than you need this triggers in your own inventory and add the triggers your self, if i install this script and read the qb-inventory or ps-inventory my server works just fine, the blackmoney and cash is working so i don't know why you can get this to work.

For other inventorys you can try to use this
https://github.com/MaDHouSe79/mh-cashasitem?tab=readme-ov-file#triggers-you-can-use-for-your-own-inventory

And you need to check if the `itemData` and `src` match with your inventory and if this is a table and the same info in it, if not, than you need to tweak your inventory, this script does nothing more dan update the cash and blackmoney and this only works when you open the inventory, so the issue is not this script but you place the triggers wrong or you forget something, cause if i install it works.

**Comment by ItsJustifY** [comment]
@MaDHouSe79 i used the qb-inventory README with ps-inventory and it works perfectly fine whereas if i follow the ps-inventory README then i get that SCRIPT ERROR: Execution of native 000000002f7a49e6 in script host failed: Argument at index 1 was null.

**Comment by MaDHouSe79** [comment]
This error "SCRIPT ERROR: Execution of native 000000002f7a49e6 in script host failed: Argument at index 1 was null." is that the server can't find a player id to send information. host failed(server) index(player id)

on what part of the code you get this error when you install the ps-inventory readme.md, 
cause there is no line number in the error, that makes it hard to find where it is.
so if you know when and where this happens, then i can take a look to fix it, 
and this is only possible if I know exactly when it happens and what you did so far when this occurs.
